# Variable 'SonarToken' was defined in the Variables tab
# Agent Queue 'Azure Pipelines' was used with unrecognized Agent Specification, vmImage property must be specified to determine image - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: WebServer_Job
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: PythonScript@0
    displayName: Run a Python script
    inputs:
      scriptPath: $(Build.SourceDirectory)/python_scan_logs/scan.py
  - script: |
         python -m venv logscan
         source logscan/bin/activate
         python -m pip install --upgrade pip
         pip install setup
         pip install -r requirements.txt
         
...
